import { db } from '@/db';
import { libraryBooks } from '@/db/schema';

async function main() {
    const sampleBooks = [
        // Computer Science (15 books)
        {
            title: 'Introduction to Algorithms',
            author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
            isbn: '978-0-262-03384-8',
            category: 'Computer Science',
            description: 'Comprehensive guide to algorithms covering fundamental concepts, data structures, and advanced algorithmic techniques used in computer science.',
            totalCopies: 8,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'MIT Press',
            publishedYear: 2022,
        },
        {
            title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            author: 'Robert C. Martin',
            isbn: '978-0-132-35088-4',
            category: 'Computer Science',
            description: 'Essential guide to writing clean, maintainable code with practical examples and best practices for professional software development.',
            totalCopies: 6,
            availableCopies: 6,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2020,
        },
        {
            title: 'Database System Concepts',
            author: 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan',
            isbn: '978-0-073-52332-3',
            category: 'Computer Science',
            description: 'Comprehensive coverage of database management systems including design, implementation, and advanced topics in data management.',
            totalCopies: 7,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2019,
        },
        {
            title: 'Computer Networks',
            author: 'Andrew S. Tanenbaum, David J. Wetherall',
            isbn: '978-0-132-12678-9',
            category: 'Computer Science',
            description: 'Detailed exploration of computer networking concepts, protocols, and architectures from physical layer to application layer.',
            totalCopies: 5,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2021,
        },
        {
            title: 'Artificial Intelligence: A Modern Approach',
            author: 'Stuart Russell, Peter Norvig',
            isbn: '978-0-134-61099-3',
            category: 'Computer Science',
            description: 'Comprehensive introduction to artificial intelligence covering intelligent agents, problem-solving, knowledge representation, and machine learning.',
            totalCopies: 10,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2020,
        },
        {
            title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
            author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
            isbn: '978-0-201-63361-0',
            category: 'Computer Science',
            description: 'Classic guide to software design patterns providing reusable solutions to common programming problems in object-oriented design.',
            totalCopies: 4,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Addison-Wesley',
            publishedYear: 2018,
        },
        {
            title: 'Operating System Concepts',
            author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
            isbn: '978-1-119-32091-3',
            category: 'Computer Science',
            description: 'Fundamental concepts of operating systems including process management, memory management, file systems, and security.',
            totalCopies: 9,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'Wiley',
            publishedYear: 2021,
        },
        {
            title: 'Python Crash Course',
            author: 'Eric Matthes',
            isbn: '978-1-593-27928-8',
            category: 'Computer Science',
            description: 'Fast-paced introduction to Python programming with hands-on projects covering data visualization, web applications, and game development.',
            totalCopies: 7,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: "O'Reilly Media",
            publishedYear: 2023,
        },
        {
            title: 'Data Structures and Algorithm Analysis in C++',
            author: 'Mark Allen Weiss',
            isbn: '978-0-132-84737-5',
            category: 'Computer Science',
            description: 'In-depth coverage of data structures and algorithms with C++ implementations and performance analysis.',
            totalCopies: 5,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2019,
        },
        {
            title: 'The Pragmatic Programmer',
            author: 'Andrew Hunt, David Thomas',
            isbn: '978-0-135-95705-9',
            category: 'Computer Science',
            description: 'Practical advice for software developers covering code organization, testing, debugging, and career development.',
            totalCopies: 6,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Addison-Wesley',
            publishedYear: 2020,
        },
        {
            title: 'Computer Organization and Design',
            author: 'David A. Patterson, John L. Hennessy',
            isbn: '978-0-128-20107-4',
            category: 'Computer Science',
            description: 'Hardware-software interface covering computer architecture, instruction sets, and performance optimization.',
            totalCopies: 4,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Morgan Kaufmann',
            publishedYear: 2020,
        },
        {
            title: 'Web Development with Node and Express',
            author: 'Ethan Brown',
            isbn: '978-1-492-05351-4',
            category: 'Computer Science',
            description: 'Comprehensive guide to building web applications using Node.js and Express framework with modern JavaScript practices.',
            totalCopies: 5,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: "O'Reilly Media",
            publishedYear: 2022,
        },
        {
            title: 'Machine Learning: A Probabilistic Perspective',
            author: 'Kevin P. Murphy',
            isbn: '978-0-262-01802-9',
            category: 'Computer Science',
            description: 'Comprehensive introduction to machine learning using probabilistic and statistical methods with practical applications.',
            totalCopies: 6,
            availableCopies: 6,
            coverImageUrl: null,
            publisher: 'MIT Press',
            publishedYear: 2023,
        },
        {
            title: 'Software Engineering: A Practitioner\'s Approach',
            author: 'Roger S. Pressman, Bruce R. Maxim',
            isbn: '978-1-259-25397-3',
            category: 'Computer Science',
            description: 'Complete guide to software engineering principles, methodologies, and best practices for professional software development.',
            totalCopies: 8,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2019,
        },
        {
            title: 'Deep Learning',
            author: 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
            isbn: '978-0-262-03561-3',
            category: 'Computer Science',
            description: 'Comprehensive resource on deep learning covering neural networks, optimization algorithms, and applications in computer vision and NLP.',
            totalCopies: 7,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'MIT Press',
            publishedYear: 2021,
        },

        // Mathematics (10 books)
        {
            title: 'Calculus: Early Transcendentals',
            author: 'James Stewart',
            isbn: '978-1-285-74155-0',
            category: 'Mathematics',
            description: 'Comprehensive calculus textbook covering limits, derivatives, integrals, and applications with clear explanations and examples.',
            totalCopies: 10,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Cengage Learning',
            publishedYear: 2020,
        },
        {
            title: 'Discrete Mathematics and Its Applications',
            author: 'Kenneth H. Rosen',
            isbn: '978-1-259-67651-2',
            category: 'Mathematics',
            description: 'Essential discrete mathematics topics including logic, sets, relations, graph theory, and combinatorics with computer science applications.',
            totalCopies: 8,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2019,
        },
        {
            title: 'Linear Algebra and Its Applications',
            author: 'Gilbert Strang',
            isbn: '978-0-030-10567-8',
            category: 'Mathematics',
            description: 'Modern approach to linear algebra covering vector spaces, matrix theory, eigenvalues, and applications in science and engineering.',
            totalCopies: 9,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Cengage Learning',
            publishedYear: 2021,
        },
        {
            title: 'Introduction to Probability',
            author: 'Dimitri P. Bertsekas, John N. Tsitsiklis',
            isbn: '978-1-886-52923-8',
            category: 'Mathematics',
            description: 'Comprehensive introduction to probability theory covering random variables, distributions, and statistical inference.',
            totalCopies: 6,
            availableCopies: 6,
            coverImageUrl: null,
            publisher: 'Athena Scientific',
            publishedYear: 2020,
        },
        {
            title: 'Abstract Algebra',
            author: 'David S. Dummit, Richard M. Foote',
            isbn: '978-0-471-43334-7',
            category: 'Mathematics',
            description: 'Comprehensive treatment of abstract algebra including group theory, ring theory, and field theory with applications.',
            totalCopies: 5,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: 'Wiley',
            publishedYear: 2018,
        },
        {
            title: 'Real Analysis',
            author: 'H. L. Royden, P. M. Fitzpatrick',
            isbn: '978-0-131-43747-0',
            category: 'Mathematics',
            description: 'Advanced treatment of real analysis covering measure theory, integration, and functional analysis.',
            totalCopies: 4,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2019,
        },
        {
            title: 'Differential Equations with Applications',
            author: 'George F. Simmons',
            isbn: '978-0-070-57540-1',
            category: 'Mathematics',
            description: 'Practical approach to differential equations with emphasis on modeling and applications in science and engineering.',
            totalCopies: 7,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2020,
        },
        {
            title: 'Introduction to Mathematical Statistics',
            author: 'Robert V. Hogg, Joseph W. McKean, Allen T. Craig',
            isbn: '978-0-321-79542-5',
            category: 'Mathematics',
            description: 'Comprehensive introduction to mathematical statistics covering estimation, hypothesis testing, and regression analysis.',
            totalCopies: 6,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2021,
        },
        {
            title: 'Number Theory',
            author: 'George E. Andrews',
            isbn: '978-0-486-68252-5',
            category: 'Mathematics',
            description: 'Introduction to elementary number theory covering divisibility, congruences, prime numbers, and Diophantine equations.',
            totalCopies: 3,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'Dover Publications',
            publishedYear: 2019,
        },
        {
            title: 'Mathematical Methods for Physics and Engineering',
            author: 'K. F. Riley, M. P. Hobson, S. J. Bence',
            isbn: '978-0-521-86153-3',
            category: 'Mathematics',
            description: 'Comprehensive reference covering mathematical techniques essential for physics and engineering applications.',
            totalCopies: 5,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Cambridge University Press',
            publishedYear: 2020,
        },

        // Physics (8 books)
        {
            title: 'University Physics with Modern Physics',
            author: 'Hugh D. Young, Roger A. Freedman',
            isbn: '978-0-135-15982-8',
            category: 'Physics',
            description: 'Comprehensive physics textbook covering mechanics, thermodynamics, electromagnetism, optics, and modern physics.',
            totalCopies: 9,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2019,
        },
        {
            title: 'Introduction to Quantum Mechanics',
            author: 'David J. Griffiths, Darrell F. Schroeter',
            isbn: '978-1-107-18963-8',
            category: 'Physics',
            description: 'Clear introduction to quantum mechanics covering wave functions, operators, angular momentum, and applications.',
            totalCopies: 6,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Cambridge University Press',
            publishedYear: 2020,
        },
        {
            title: 'Classical Mechanics',
            author: 'John R. Taylor',
            isbn: '978-1-891-38922-1',
            category: 'Physics',
            description: 'Modern approach to classical mechanics covering Lagrangian and Hamiltonian formulations with applications.',
            totalCopies: 5,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'University Science Books',
            publishedYear: 2021,
        },
        {
            title: 'Introduction to Electrodynamics',
            author: 'David J. Griffiths',
            isbn: '978-1-108-42041-9',
            category: 'Physics',
            description: 'Comprehensive treatment of electromagnetic theory covering electrostatics, magnetostatics, and electrodynamics.',
            totalCopies: 7,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Cambridge University Press',
            publishedYear: 2022,
        },
        {
            title: 'Thermal Physics',
            author: 'Charles Kittel, Herbert Kroemer',
            isbn: '978-0-716-71088-6',
            category: 'Physics',
            description: 'Introduction to thermodynamics and statistical mechanics with emphasis on physical understanding and applications.',
            totalCopies: 4,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'W. H. Freeman',
            publishedYear: 2019,
        },
        {
            title: 'Optics',
            author: 'Eugene Hecht',
            isbn: '978-0-133-97722-6',
            category: 'Physics',
            description: 'Comprehensive coverage of optical phenomena including wave optics, interference, diffraction, and modern applications.',
            totalCopies: 5,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2020,
        },
        {
            title: 'Solid State Physics',
            author: 'Neil W. Ashcroft, N. David Mermin',
            isbn: '978-0-030-83993-1',
            category: 'Physics',
            description: 'Advanced treatment of solid state physics covering crystal structures, band theory, and electronic properties.',
            totalCopies: 3,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Cengage Learning',
            publishedYear: 2018,
        },
        {
            title: 'Nuclear and Particle Physics',
            author: 'Brian R. Martin',
            isbn: '978-0-470-74275-4',
            category: 'Physics',
            description: 'Introduction to nuclear structure, radioactivity, elementary particles, and fundamental interactions.',
            totalCopies: 4,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'Wiley',
            publishedYear: 2021,
        },

        // Engineering (10 books)
        {
            title: 'Microelectronic Circuits',
            author: 'Adel S. Sedra, Kenneth C. Smith',
            isbn: '978-0-199-33913-6',
            category: 'Engineering',
            description: 'Comprehensive coverage of electronic circuit design including amplifiers, feedback systems, and integrated circuits.',
            totalCopies: 8,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'Oxford University Press',
            publishedYear: 2020,
        },
        {
            title: 'Digital Design and Computer Architecture',
            author: 'David Harris, Sarah Harris',
            isbn: '978-0-123-94424-5',
            category: 'Engineering',
            description: 'Modern approach to digital logic design and computer architecture from transistors to processors.',
            totalCopies: 7,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'Morgan Kaufmann',
            publishedYear: 2021,
        },
        {
            title: 'Control Systems Engineering',
            author: 'Norman S. Nise',
            isbn: '978-1-119-47422-7',
            category: 'Engineering',
            description: 'Comprehensive introduction to control systems covering modeling, analysis, and design of feedback control systems.',
            totalCopies: 6,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Wiley',
            publishedYear: 2022,
        },
        {
            title: 'Engineering Electromagnetics',
            author: 'William H. Hayt, John A. Buck',
            isbn: '978-0-073-38075-8',
            category: 'Engineering',
            description: 'Fundamental concepts of electromagnetics with applications to transmission lines, waveguides, and antennas.',
            totalCopies: 5,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2019,
        },
        {
            title: 'Power Electronics: Converters, Applications, and Design',
            author: 'Ned Mohan, Tore M. Undeland, William P. Robbins',
            isbn: '978-1-118-23999-0',
            category: 'Engineering',
            description: 'Comprehensive treatment of power electronic circuits and systems including converters, inverters, and motor drives.',
            totalCopies: 4,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'Wiley',
            publishedYear: 2020,
        },
        {
            title: 'Signals and Systems',
            author: 'Alan V. Oppenheim, Alan S. Willsky',
            isbn: '978-0-138-14757-4',
            category: 'Engineering',
            description: 'Introduction to continuous-time and discrete-time signals and systems with Fourier and Laplace transform analysis.',
            totalCopies: 9,
            availableCopies: 6,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2021,
        },
        {
            title: 'Fundamentals of Electric Circuits',
            author: 'Charles K. Alexander, Matthew N. O. Sadiku',
            isbn: '978-0-078-02847-7',
            category: 'Engineering',
            description: 'Comprehensive introduction to circuit analysis techniques including DC, AC, and transient analysis.',
            totalCopies: 10,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2020,
        },
        {
            title: 'Digital Signal Processing',
            author: 'John G. Proakis, Dimitris G. Manolakis',
            isbn: '978-0-131-87374-2',
            category: 'Engineering',
            description: 'Comprehensive coverage of digital signal processing theory, algorithms, and applications.',
            totalCopies: 6,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2019,
        },
        {
            title: 'VLSI Design',
            author: 'Wayne Wolf',
            isbn: '978-0-130-40051-0',
            category: 'Engineering',
            description: 'Introduction to VLSI circuit design covering layout, fabrication, testing, and system-level design.',
            totalCopies: 5,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2020,
        },
        {
            title: 'Robotics, Vision and Control',
            author: 'Peter Corke',
            isbn: '978-3-319-54413-7',
            category: 'Engineering',
            description: 'Fundamental concepts of robotics including kinematics, dynamics, computer vision, and control algorithms.',
            totalCopies: 4,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Springer',
            publishedYear: 2021,
        },

        // Literature (7 books)
        {
            title: 'Pride and Prejudice',
            author: 'Jane Austen',
            isbn: '978-0-141-43951-8',
            category: 'Literature',
            description: 'Classic novel exploring themes of love, class, and social expectations in Georgian England through the Bennet family.',
            totalCopies: 5,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'Penguin Classics',
            publishedYear: 2020,
        },
        {
            title: '1984',
            author: 'George Orwell',
            isbn: '978-0-452-28423-4',
            category: 'Literature',
            description: 'Dystopian novel depicting a totalitarian society under constant surveillance and propaganda.',
            totalCopies: 6,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Signet Classic',
            publishedYear: 2019,
        },
        {
            title: 'To Kill a Mockingbird',
            author: 'Harper Lee',
            isbn: '978-0-061-12000-8',
            category: 'Literature',
            description: 'Powerful story of racial injustice and childhood innocence in the American South during the 1930s.',
            totalCopies: 7,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'Harper Perennial',
            publishedYear: 2020,
        },
        {
            title: 'The Great Gatsby',
            author: 'F. Scott Fitzgerald',
            isbn: '978-0-743-27356-5',
            category: 'Literature',
            description: 'Classic American novel exploring themes of wealth, love, and the American Dream in the Jazz Age.',
            totalCopies: 4,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Scribner',
            publishedYear: 2021,
        },
        {
            title: 'The Complete Works of William Shakespeare',
            author: 'William Shakespeare',
            isbn: '978-0-517-05361-5',
            category: 'Literature',
            description: 'Comprehensive collection of Shakespeare\'s plays and sonnets including tragedies, comedies, and histories.',
            totalCopies: 3,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'Barnes & Noble',
            publishedYear: 2019,
        },
        {
            title: 'One Hundred Years of Solitude',
            author: 'Gabriel García Márquez',
            isbn: '978-0-060-88328-8',
            category: 'Literature',
            description: 'Magical realism masterpiece chronicling seven generations of the Buendía family in the fictional town of Macondo.',
            totalCopies: 5,
            availableCopies: 1,
            coverImageUrl: null,
            publisher: 'Harper Perennial',
            publishedYear: 2020,
        },
        {
            title: 'The Norton Anthology of Poetry',
            author: 'Margaret Ferguson, Mary Jo Salter, Jon Stallworthy',
            isbn: '978-0-393-67906-5',
            category: 'Literature',
            description: 'Comprehensive collection of English and American poetry from medieval times to contemporary works.',
            totalCopies: 4,
            availableCopies: 4,
            coverImageUrl: null,
            publisher: 'W. W. Norton & Company',
            publishedYear: 2021,
        },

        // Business & Management (5 books)
        {
            title: 'Principles of Economics',
            author: 'N. Gregory Mankiw',
            isbn: '978-1-337-51689-1',
            category: 'Business & Management',
            description: 'Comprehensive introduction to economic principles covering microeconomics, macroeconomics, and current economic issues.',
            totalCopies: 8,
            availableCopies: 6,
            coverImageUrl: null,
            publisher: 'Cengage Learning',
            publishedYear: 2020,
        },
        {
            title: 'Marketing Management',
            author: 'Philip Kotler, Kevin Lane Keller',
            isbn: '978-0-134-85619-7',
            category: 'Business & Management',
            description: 'Comprehensive guide to marketing strategies, consumer behavior, branding, and digital marketing.',
            totalCopies: 6,
            availableCopies: 2,
            coverImageUrl: null,
            publisher: 'Pearson',
            publishedYear: 2021,
        },
        {
            title: 'The Lean Startup',
            author: 'Eric Ries',
            isbn: '978-0-307-88789-4',
            category: 'Business & Management',
            description: 'Revolutionary approach to building successful startups through validated learning, rapid experimentation, and iterative development.',
            totalCopies: 5,
            availableCopies: 0,
            coverImageUrl: null,
            publisher: 'Crown Business',
            publishedYear: 2019,
        },
        {
            title: 'Financial Accounting',
            author: 'Robert Libby, Patricia Libby, Frank Hodge',
            isbn: '978-1-259-96465-8',
            category: 'Business & Management',
            description: 'Introduction to financial accounting principles, financial statements, and business decision-making.',
            totalCopies: 7,
            availableCopies: 5,
            coverImageUrl: null,
            publisher: 'McGraw-Hill',
            publishedYear: 2020,
        },
        {
            title: 'Good to Great: Why Some Companies Make the Leap and Others Don\'t',
            author: 'Jim Collins',
            isbn: '978-0-066-62099-2',
            category: 'Business & Management',
            description: 'Research-based analysis of what differentiates great companies from good ones and principles for sustainable success.',
            totalCopies: 4,
            availableCopies: 3,
            coverImageUrl: null,
            publisher: 'HarperBusiness',
            publishedYear: 2021,
        },
    ];

    await db.insert(libraryBooks).values(sampleBooks);
    
    console.log('✅ Library books seeder completed successfully - 55 books added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});